### ISSUE TITLE
Fine tune results from search engine

### ISSUE THREAD

**Issue by srldl** [npolar/npdc#25]
Issue happens during search, data.npolar.no first version - should be fixed in new version:

It happens at:
https://data.npolar.no/publications/?limit=25&q=matsuoka&highlight=true&sort=-publication_year&filter-published_sort=2015-01-01T00:00:00Z..2016-01-01T00:00:00Z

When I selected publication and 2015, and specify my name.

Kenny

![search hightlighted](https://cloud.githubusercontent.com/assets/3511620/10157557/4dadb6d4-668b-11e5-81e1-09cc402bd833.png)

**Comment by cnrdh** [comment]
Please elaborate, I don't understand what is the issue here?
Probably also move this to https://github.com/npolar/npdc-publication

**Comment by srldl** [comment]
The whole object is shown in search results below the title - words like "author" etc in the search result shouldn't be there, just person names and name of dataset/publication/project etc

**Comment by cnrdh** [comment]
Well we don't have hit highlighting in the new NPDC, so I close this
