### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by baelter** [npolar/npdc#5]
Define deploy strategy. Automate what can be automated.

**Comment by cnrdh** [comment]
Plan is to deploy from git relases, and use travis to build git releases, ie. without needing to add "dist" folder to git

**Comment by cnrdh** [comment]
http://docs.travis-ci.com/user/deployment/releases/

**Comment by cnrdh** [comment]
Meant git branches.

And the deploy tools could maybe create these and handle stuff like version bumping?
